# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [16]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint
#from census import Census

# Import API key
from api_keys import g_key

# # Access maps with unique API key
# gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [17]:
# Output File (CSV)
city_data = pd.read_csv("../output_data/cities.csv")
city_data = city_data.dropna()
city_data.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,2123814,leningradskiy,RU,1643916953,69.3833,178.4167,-12.35,84,2,8.23
1,2264557,ponta do sol,PT,1643916945,32.6667,-17.1000,68.00,72,38,4.21
2,4030556,rikitea,PF,1643917228,-23.1203,-134.9692,77.58,77,100,15.77
3,4020109,atuona,PF,1643916943,-9.8000,-139.0333,78.30,72,0,12.84
4,5880054,barrow,US,1643917228,71.2906,-156.7887,-27.38,75,20,4.61

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [18]:
weather_criteria = city_data[
    (city_data['Max Temp'] < 80) & 
    (city_data['Max Temp'] >70) & 
    (city_data['Wind Speed'] < 10) & 
    (city_data['Cloudiness'] == 0)]

weather_criteria = weather_criteria.dropna()

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [19]:
hotel_df = weather_criteria
hotel_df['hotel_name'] = " "
hotel_df['hotel_address'] = " "
hotel_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,hotel_name,hotel_address
114,3932145,pisco,PE,1643917257,-13.7000,-76.2167,73.45,73,0,6.91,,
130,286621,salalah,OM,1643917261,17.0151,54.0924,75.29,73,0,1.14,,
160,5850554,makakilo city,US,1643917271,21.3469,-158.0858,76.28,59,0,5.75,,
178,5855927,hilo,US,1643917230,19.7297,-155.0900,76.12,64,0,4.61,,
200,5848280,kapaa,US,1643917282,22.0752,-159.3190,75.47,71,0,1.01,,

In [26]:
for index, row in hotel_df.iterrows():
    #target = f"{row['City']}, {row['Country']}"
    #print(f"calling geocode with target: {target}")
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    params = {
        "location": f"{row['Lat']}, {row['Lng']}",
        "type": "lodging",
        "radius": "5000",
        #"rankby": "distance",
        "key": g_key
        }
    #pprint(params)
    
    places_data = requests.get(base_url, params=params).json()

    try:
        hotel_df.loc[index, 'hotel_name'] = places_data["results"][0]["name"]
        hotel_df.loc[index, 'hotel_address'] = places_data["results"][0]["vicinity"]
    
    except Exception as error:
        print(error)
        
#pprint(places_data)

list index out of range

In [27]:
hotel_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,hotel_name,hotel_address
114,3932145,pisco,PE,1643917257,-13.7000,-76.2167,73.45,73,0,6.91,Hotel San Isidro Oficial,"Calle, Pisco"
130,286621,salalah,OM,1643917261,17.0151,54.0924,75.29,73,0,1.14,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel",Salalah
160,5850554,makakilo city,US,1643917271,21.3469,-158.0858,76.28,59,0,5.75,Marriott's Ko Olina Beach Club,92-161 Waipahe Place Marriott Vacation Club Ka...
178,5855927,hilo,US,1643917230,19.7297,-155.0900,76.12,64,0,4.61,Hilo Hawaiian Hotel,"71 Banyan Drive, Hilo"
200,5848280,kapaa,US,1643917282,22.0752,-159.3190,75.47,71,0,1.01,Sheraton Kauai Coconut Beach Resort,"650 Aleka Loop, Kapaʻa"
222,2358100,manga,BF,1643917289,11.6636,-1.0731,77.11,9,0,6.55,Auberge du 11 décembre de la cité CNSS à Manga,"N17, Manga"
409,2070998,geraldton,AU,1643917254,-28.7667,114.6000,70.21,52,0,8.05,Broadwater Mariner Resort,"298 Chapman Road, Geraldton"
456,2414544,tougue,GN,1643917361,11.4667,-11.6000,71.31,15,0,2.42,,
503,3374210,sao filipe,CV,1643917374,14.8961,-24.4956,73.74,74,0,7.00,Hotel Xaguate,"Sao Filipe, Rua da Posto, Fogo"
532,2291136,bondoukou,CI,1643917385,8.0333,-2.8000,78.69,12,0,3.18,Prestige Hotel,"30 m de la présidence, route abema, Bondoukou"

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure